document.addEventListener('DOMContentLoaded', () => {
    const quoteContainer = document.getElementById('quote-container');
    const quoteText = document.getElementById('quote');
    const authorText = document.getElementById('author');
    const newQuoteBtn = document.getElementById('new-quote');

    const quotes = [
        { content: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
        { content: "Arise, awake, and stop not till the goal is reached.", author: "Swami Vivekananda" },
        { content: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
        { content: "The future depends on what we do in the present.", author: "Mahatma Gandhi" },
        { content: "Take risks in your life. If you win, you can lead. If you lose, you can guide.", author: "Swami Vivekananda" },
        { content: "When you are inspired by some great purpose, all your thoughts break their bonds.", author: "Patanjali" },
        { content: "All power is within you; you can do anything and everything.", author: "Swami Vivekananda" },
        { content: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
        { content: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
        { content: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
        { content: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
        { content: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
        { content: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
        { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
        { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
        { content: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
        { content: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
        { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
        { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
        { content: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
        { content: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
        { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
        { content: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
        { content: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
        { content: "Act as if what you do makes a difference. It does.", author: "William James" },
        { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
        { content: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
        { content: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
        { content: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
        { content: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
        { content: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
        { content: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
        { content: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
        { content: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
        { content: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
        { content: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
        { content: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
        { content: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
        { content: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
        { content: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
        { content: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
        { content: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
        { content: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
        { content: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
        { content: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
        { content: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
        { content: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
        { content: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
        { content: "The best way to predict your future is to create it.", author: "Peter Drucker" },
        { content: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
        { content: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
        { content: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
        { content: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
        { content: "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.", author: "Steve Jobs" },
        { content: "People who are crazy enough to think they can change the world, are the ones who do.", author: "Rob Siltanen" },
        { content: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
        { content: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
        { content: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang Von Goethe" },
        { content: "Imagine your life is perfect in every respect; what would it look like?", author: "Brian Tracy" },
        { content: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link" },
        { content: "Whether you think you can or think you can’t, you’re right.", author: "Henry Ford" },
        { content: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller" },
        { content: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
        { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
        { content: "Creativity is intelligence having fun.", author: "Albert Einstein" },
        { content: "What you lack in talent can be made up with desire, hustle and giving 110% all the time.", author: "Don Zimmer" },
        { content: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
        { content: "Develop an ‘Attitude of Gratitude’. Say thank you to everyone you meet for everything they do for you.", author: "Brian Tracy" },
        { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
        { content: "To see what is right and not do it is a lack of courage.", author: "Confucius" },
        { content: "Reading is to the mind, as exercise is to the body.", author: "Brian Tracy" },
        { content: "Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality.", author: "Brian Tracy" },
        { content: "The future belongs to the competent. Get good, get better, be the best!", author: "Brian Tracy" },
        { content: "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.", author: "Jack Canfield" },
        { content: "Things work out best for those who make the best of how things work out.", author: "John Wooden" },
        { content: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
        { content: "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.", author: "Michael Phelps" },
        { content: "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.", author: "Michelle Obama" },
        { content: "Today’s accomplishments were yesterday’s impossibilities.", author: "Robert H. Schuller" },
        { content: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
        { content: "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got to keep going.", author: "Chantal Sutherland" },
        { content: "A goal is not always meant to be reached; it often serves simply as something to aim at.", author: "Bruce Lee" },
        { content: "No matter how hard the past, you can always begin again.", author: "Buddha" },
        { content: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
        { content: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
        { content: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
        { content: "संघर्ष जितना बड़ा होगा, जीत उतनी ही शानदार होगी।", author: "अवध ओझा" },
        { content: "तुम्हारी हार तब तक नहीं होती जब तक तुम खुद हार नहीं मान लेते।", author: "अवध ओझा" },
        { content: "अपने सपनों को साकार करने के लिए मेहनत करो, क्योंकि सफलता आराम करने से नहीं मिलती।", author: "अवध ओझा" },
        { content: "सपने वो नहीं जो हम सोते वक्त देखते हैं, सपने वो हैं जो हमें सोने नहीं देते।", author: "अवध ओझा" },
        { content: "अगर आपको लगता है कि आप कर सकते हैं, तो आप सही हैं। अगर आपको लगता है कि आप नहीं कर सकते हैं, तो भी आप सही हैं।", author: "अवध ओझा" },
        { content: "जितना बड़ा सपना, उतनी बड़ी मुश्किलें। लेकिन जो इन मुश्किलों से नहीं घबराता, वही असली विजेता होता है।", author: "अवध ओझा" },
        { content: "हारने वाले वही होते हैं, जो कभी प्रयास नहीं करते।", author: "अवध ओझा" },
        { content: "हर समस्या का समाधान होता है, बस उसे खोजने की देर है।", author: "अवध ओझा" },
        { content: "अगर आप सफल होना चाहते हैं, तो अपने दिल की सुनो और अपनी मेहनत पर विश्वास करो।", author: "अवध ओझा" },
        { content: "कठिनाइयाँ आपके रास्ते में तभी आती हैं जब आप सही रास्ते पर होते हैं।", author: "अवध ओझा" },
        { content: "सफलता का कोई शॉर्टकट नहीं होता, मेहनत ही एकमात्र तरीका है।", author: "अवध ओझा" },
        { content: "आपकी मेहनत का फल जरूर मिलेगा, बस धैर्य और विश्वास बनाए रखें।", author: "अवध ओझा" },
        { content: "जिन्होंने अपने सपनों को साकार किया है, वे कभी हार नहीं मानते।", author: "अवध ओझा" },
        { content: "आपका आज का संघर्ष ही आपके आने वाले कल की नींव है।", author: "अवध ओझा" },
        { content: "मेहनत से डरना छोड़ो, क्योंकि मेहनत ही सफलता की कुंजी है।", author: "अवध ओझा" },
        { content: "अगर आप सच में कुछ पाना चाहते हैं, तो आपको उसे पाने के लिए हर संभव कोशिश करनी होगी।", author: "अवध ओझा" },
        { content: "जो व्यक्ति खुद पर विश्वास करता है, वही सबसे बड़ा योद्धा होता है।", author: "अवध ओझा" },
        { content: "जिंदगी में कोई भी चीज आसान नहीं होती, बस हमें उसे हासिल करने का जुनून होना चाहिए।", author: "अवध ओझा" },
        { content: "सपने देखने वालों को ही सपने पूरे करने का मौका मिलता है।", author: "अवध ओझा" },
        { content: "आपकी मेहनत का फल जरूर मिलेगा, बस उसे पाने का हौसला बनाए रखें।", author: "अवध ओझा" },
        { content: "जो व्यक्ति कभी हार नहीं मानता, वही सच्चा विजेता होता है।", author: "अवध ओझा" },
        { content: "आपका संघर्ष ही आपकी पहचान है, इसलिए कभी संघर्ष से घबराओ मत।", author: "अवध ओझा" },
        { content: "जो लोग अपने सपनों को साकार करना चाहते हैं, उन्हें मेहनत से कभी डरना नहीं चाहिए।", author: "अवध ओझा" },
        { content: "सफलता का रास्ता कभी आसान नहीं होता, लेकिन मेहनत करने वालों के लिए वो रास्ता भी आसान हो जाता है।", author: "अवध ओझा" },
        { content: "अगर आप मेहनत करोगे तो सफलता खुद ब खुद आपके पास आ जाएगी।", author: "अवध ओझा" },
        { content: "हर मुश्किल का सामना करना सीखो, क्योंकि मुश्किलें ही आपको मजबूत बनाती हैं।", author: "अवध ओझा" },
        { content: "जो लोग अपने सपनों को साकार करना चाहते हैं, उन्हें अपने लक्ष्य के प्रति समर्पित होना चाहिए।", author: "अवध ओझा" },
        { content: "सपने वही सच होते हैं, जिनमें मेहनत की जाती है।", author: "अवध ओझा" },
        { content: "जो लोग अपने सपनों को साकार करना चाहते हैं, उन्हें कभी हार नहीं माननी चाहिए।", author: "अवध ओझा" },
        { content: "हर किसी के जीवन में संघर्ष होता है, लेकिन उसे पार करना ही असली जीत है।", author: "अवध ओझा" },
        { content: "आपका संघर्ष ही आपकी सफलता की गारंटी है।", author: "अवध ओझा" },
        { content: "अगर आप मेहनत करेंगे, तो सफलता आपके कदम चूमेगी।", author: "अवध ओझा" },
        { content: "हर मुश्किल को पार करोगे, अगर आपका हौसला बुलंद होगा।", author: "अवध ओझा" },
        { content: "मेहनत का फल हमेशा मीठा होता है, बस उसे पाने का हौसला होना चाहिए।", author: "अवध ओझा" },
        { content: "सपनों को साकार करने का सबसे अच्छा तरीका है, मेहनत करना।", author: "अवध ओझा" },
        { content: "जो लोग अपने सपनों को साकार करना चाहते हैं, उन्हें कभी हार नहीं माननी चाहिए।", author: "अवध ओझा" },
        { content: "सपनों को साकार करने के लिए मेहनत ही एकमात्र तरीका है।", author: "अवध ओझा" },
        { content: "सपनों को साकार करने के लिए मेहनत करना बहुत जरूरी है।", author: "अवध ओझा" },
        { content: "आपका संघर्ष ही आपकी सफलता की गारंटी है।", author: "अवध ओझा" },
        { content: "जो लोग अपने सपनों को साकार करना चाहते हैं, उन्हें कभी हार नहीं माननी चाहिए।", author: "अवध ओझा" },
        { content: "तुम जो हो, तुम्हारा अनुभव जो है, वही तुम्हारी पहचान है।", author: "आचार्य प्रशांत" },
        { content: "जितना आत्म-विश्वास तुम अपनी क्षमता में रखोगे, उतना ही तुम्हारी सफलता का रास्ता स्पष्ट होगा।", author: "आचार्य प्रशांत" },
        { content: "अपने सपनों को पूरा करने के लिए आपको सपनों के पीछे नहीं, सपनों के पीछे भागना होगा।", author: "अलख पांडे" },
        { content: "जब आपके सपने आपकी नींव बन जाते हैं, तो उन्हें पूरा करने के लिए कुछ नहीं आपके रास्ते में रुकावट बन सकती है।", author: "अलख पांडे" },
        { content: "संघर्ष वह नहीं, जिसमें सफलता मिले, संघर्ष वह है, जिससे हम सीखते हैं।", author: "अलख पांडे" },
        { content: "हमें हमेशा वही मिलता है जो हम प्राप्त करने के लायक होते हैं।", author: "अलख पांडे" },
        { content: "जीतना उसी का नाम है, जो हारने के डर से नहीं, अपने विचारों और क्रियाओं में सफल होता है।", author: "अलख पांडे" },
        { content: "सपने वहां से आरंभ होते हैं, जहां हम अपनी सीमाओं को पार करते हैं।", author: "अलख पांडे" },
        { content: "अपने कर्मों को वजन देने वाली सबसे अच्छी बात यह है कि यह हमें उन्नति के मार्ग पर ले जाती है।", author: "अलख पांडे" },
        { content: "अगर हम सपने देख सकते हैं, तो हम उन्हें पूरा भी कर सकते हैं।", author: "अलख पांडे" },
        { content: "आपकी सोच आपकी शक्ति का परिणाम है।", author: "अलख पांडे" },
        { content: "स्वप्न जो आपको जागने की साहसिकता देते हैं।", author: "अलख पांडे" }

    ];

    function getQuote() {
        const randomIndex = Math.floor(Math.random() * quotes.length);
        const selectedQuote = quotes[randomIndex];
        quoteText.textContent = `"${selectedQuote.content}"`;
        authorText.textContent = `- ${selectedQuote.author}`;
        quoteContainer.classList.add('fade-in');
        setTimeout(() => quoteContainer.classList.remove('fade-in'), 1000);
    }

    newQuoteBtn.addEventListener('click', getQuote);

    // Fetch the first quote on load
    getQuote();
});
